config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  devise_for :users, class_name: "User", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [ :index ]
    resources :ice_creams
  end
  resources :ices, only: [ :index, :show, :new, :create ]

  resources :ajigraf, only: [ :index, :new, :create ] do
    collection do
      get "result", to: "ajigraf#result"
    end
  end

  # ネストされたルーティング(reviewsはice_creamsの子リソース)
  resources :ice_creams,  only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
    collection do
      get :favorites
      get :tags
      get :gotouchi
      get :calorie
    end
  end

  resources :favorites, only: [ :create, :destroy, :index ]

  resources :todayice, only: [ :index ] do
    collection do
      get "result"
    end
  end

  resources :images, only: [] do
    collection do
      get :ajigraf
      get :todayice
    end
  end

  resources :quizzes, only: [ :index ] do
    collection do
      post :check
      get :result
      get :explanation
    end
  end

  get "rakuten_search" => "ice_creams#search"


  devise_for :admins,
    controllers: { sessions: "admin/sessions" },
    path: "admin",
    skip: [ :registrations, :passwords ]

  post "/callback" => "linebot#callback"

  namespace :api do
    resources :ice_creams, only: [ :index ]
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/ajigraf_controller.rb
class AjigrafController < ApplicationController
  skip_before_action :authenticate_user!, raise: false
  def index
  end
  def new
    @chart = Chart.new
    @ice_creams = IceCream.all
  end

  def create
    # user_signed_in?のときはcurrent_user.idを、そうでないときはnilを設定
    user_id = user_signed_in? ? current_user.id : nil
    # 受け取ったchart_paramsにchart_type: "user", user_id: user_idをマージ（追加）する
    @chart = Chart.new(chart_params.merge(chart_type: "user", user_id: user_id))
    if @chart.save
      redirect_to result_ajigraf_index_path(chart_id: @chart.id)
    else
      render :new
    end
  end

  def result
    @chart = Chart.find(params[:chart_id])
    # ice_creamモデルに定義されたto_vectorメソッドを使用して、チャートを数値化
    user_vec = @chart.to_vector

    charts_for_ice = Chart.where(chart_type: [ :official, :user_post ]).includes(ice_cream: [ :image_attachment ]).where.not(ice_cream_id: nil)

    closest_chart = charts_for_ice.min_by { |c| euclidean_distance(user_vec, c.to_vector) }
    @closest_chart = closest_chart
    @closest_ice   = closest_chart&.ice_cream

    if @closest_ice.nil?
      redirect_to new_ajigraf_path, alert: "おすすめのアイスが見つかりませんでした。もう一度試してください。"
      return
    end

    prepare_meta_tags
  end

  private

  def chart_params
    params.require(:chart).permit(:sweetness, :freshness, :richness, :calorie, :ingredient_richness, :ice_cream_id)
  end

  def euclidean_distance(vector1, vector2)
    # ユークリッド距離を計算
    Math.sqrt(vector1.zip(vector2).map { |a, b| (a - b) ** 2 }.sum)
  end


  def prepare_meta_tags
    # CGI.escapeメソッドを使用して、アイスクリームの名前をURLエンコード(urlで文字列は使用できない)
    image_url = "#{request.base_url}/images/ajigraf?text=#{CGI.escape(@closest_ice.name)}"
    # set_meta_tagsメソッドを使用して、OGPとTwitterカードのメタタグを設定
    set_meta_tags og: {
                    title: "あなたにピッタリなアイスは#{@closest_ice.name}!",
                    description: "#{@closest_ice.name}があなたにおすすめのアイスです！",
                    type: "website",
                    url: request.original_url,
                    image: image_url
                  },
                  twitter: {
                    card: "summary_large_image",
                    title: "あなたにピッタリなアイスは#{@closest_ice.name}!",
                    description: "#{@closest_ice.name}があなたにおすすめのアイスです！",
                    image: image_url
                  }
  end
end

app/views/ajigraf/_favorite.html.erb
<%= link_to favorites_path(ice_cream_id: ice_cream.id), id: "js-favotite-button-for-ice_cream-#{ice_cream.id}",  data: { turbo_method: :post } do %>
    <iconify-icon icon="mdi:heart-outline" width="24" height="24" class="text-red-500"></iconify-icon>
<% end %>

app/views/ajigraf/_favorite_button.html.erb
<% if current_user %>    
    <% if current_user.favorite?(ice_cream) %>
        <%= render 'unfavorite', {ice_cream: ice_cream} %>
    <% else %>
        <%= render 'favorite', {ice_cream: ice_cream} %>    
    <% end %>
<% end %>

app/views/ajigraf/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(ice_cream_id: ice_cream.id)), id: "js-favorite-button-for-ice_cream-#{ice_cream.id}",  data: { turbo_method: :delete} do %>
    <iconify-icon icon="mdi:heart" width="24" height="24" class="text-red-500"></iconify-icon>
<% end %>


app/views/ajigraf/new.html.erb
<h1 class="pt-10 font-kiwi text-4xl text-black-600 text-center ">
    あじぐらふ
</h1>
<h3 class="text-center font-kiwi text-md sm:text-lg mt-4 px-4">
    5段階のレーダーチャートであなたにピッタリなあいすを診断します🍧
</h3>
<h3 class="text-center font-kiwi text-md sm:text-lg mt-2 px-4">
    味の好みやあいすの特徴を５段階で入力してください🍨
</h3>
<div class="mx-auto bg-amber-50 shadow-md rounded-3xl mt-6 mb-6 px-4 pt-4 max-w-5xl">
    <div class="flex justify-center md:justify-end md:pr-72">
        <div class="flex justify-between text-sm text-gray-500 px-2 w-60 font-kiwi">
            <span>←低い</span>
            <span>高い→</span> 
        </div>
    </div>
    <div class="flex justify-center md:justify-end md:pr-72">
        <div class="flex justify-between text-sm text-gray-500 px-2 w-60 font-kiwi">
            <span>1</span>
            <span>2</span>
            <span>3</span>  
            <span>4</span>
            <span>5</span>
        </div>
    </div>
    <%= form_with model: @chart,url: ajigraf_index_path, local: true, class: "mt-10" do |form| %>
        <div class="flex justify-between items-center mt-4 px-4 sm:px-80">
            <%= form.label :sweetness, "甘さ", class: "font-kiwi text-lg " %>
            <%= form.range_field :sweetness, in: 1..5, class: "ml-2 border rounded p-2 accent-orange-400" %>
        </div>
        <div class="flex justify-between items-center mt-4 px-4 sm:px-80">
            <%= form.label :freshness, "爽やかさ", class: "font-kiwi text-lg" %>
            <%= form.range_field :freshness, in: 1..5, class: "ml-2 border rounded p-2 accent-orange-400" %>
        </div>
        <div class="flex justify-between items-center mt-4 px-4 sm:px-80">
            <%= form.label :richness, "濃厚さ", class: "font-kiwi text-lg" %>
            <%= form.range_field :richness, in: 1..5, class: "ml-2 border rounded p-2 accent-orange-400" %>
        </div>
        <div class="flex justify-between items-center mt-4 px-4 sm:px-80">
            <%= form.label :calorie, "カロリー", class: "font-kiwi text-lg" %>
            <%= form.range_field :calorie, in: 1..5, class: "ml-2 border rounded p-2 accent-orange-400" %>
        </div>
        <div class="flex justify-between items-center mt-4 px-4 sm:px-80">
            <%= form.label :ingredient_richness, "具材のリッチさ", class: "font-kiwi text-lg" %>
            <%= form.range_field :ingredient_richness, in: 1..5, class: "ml-2 border rounded p-2 accent-orange-400" %>
        </div>
        <div class="flex justify-center mt-6 pb-6">
            <%= form.submit "あなたにぴったりなあいすを探す", class: "bg-stone-300 hover:bg-stone-400 text-stone-800 font-kiwi py-2 sm:py-4 px-4 sm:px-8 text-xs sm:text-lg rounded-3xl w-56 md:w-96 " %>
        </div>
    <% end %>
</div>

app/views/ajigraf/result.html.erb
<div class="pt-10 font-kiwi text-4xl text-black-600 text-center">
    あなたにピッタリなアイスは…
</div>


<div class="mx-auto bg-amber-50 shadow-md rounded-3xl  p-6 max-w-5xl mt-6 text-center  px-6 sm:px-8 lg:px-16">
    <%= turbo_frame_tag "ajigraf_result" do %>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div class="pl-4">
                <div class="flex flex-col items-center mt-6">
                    <h1 class="text-4xl font-kiwi"> <%= @closest_ice.name %> </h1>
                    <%= link_to '🔎このあいすの詳細', ice_cream_path(@closest_ice), data: { turbo: false} ,class: ' hover:underline mt-2' %>
                    <h2 class="text-3xl font-kiwi"> <%= @closest_ice.comment %> </h2>
                    <% if @closest_ice.image.attached? %>
                        <h3 class="pt-10"><%= image_tag @closest_ice.image, class: 'h-40 w-auto' %></h3>
                    <% else %>
                        <h3 class="pt-10"><%= image_tag 'Icecream.png', class: 'h-40 w-auto' %></h3>
                    <% end %>    
                </div>
            </div>
            <div class="pl-4">
                <div data-controller="ice-cream-chart"
                    data-ice-cream-chart-chart-data-value="<%= @closest_chart.to_vector.to_json %>"
                    data-ice-cream-chart-labels-value="<%= ['甘さ', '爽やかさ', '濃厚さ', 'カロリー', '具材の充実感'].to_json %>">
                    <canvas data-ice-cream-chart-target="canvas" width="400" height="200"></canvas>
                </div>
            </div>
        </div>
    <% end %>

    <div class="pt-4 flex justify-center mt-auto">
        <%= render 'favorite_button', ice_cream: @closest_ice %>
    </div>


    <div class="flex justify-center mt-6 pb-6">
        <%= link_to 'もう一度！', new_ajigraf_path, class: "bg-stone-300 hover:bg-stone-400 text-stone-800 font-kiwi py-2 sm:py-4 px-4 sm:px-8 text-xs sm:text-lg rounded-3xl w-56 md:w-56 " %>
    </div>
    
    <div class="twitter pt-5 flex justify-center font-kiwi gap-4 mt-1">
        <%= link_to "https://twitter.com/intent/tweet?" +"text=あなたにピッタリなあいすは#{@closest_ice.name}!" + "&url=#{request.original_url}",  class: "bg-blue-400 hover:bg-blue-500 text-white font-kiwi py-4 px-8 text-xl rounded-3xl  flex items-center gap-2 twitter-share-button", target: "_blank", rel: "noopener" do %>
            <iconify-icon icon="simple-icons:x" width="24" height="24"></iconify-icon>
            <span>結果をツイートする</span>
        <% end %>
    </div>
</div>