config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  devise_for :users, class_name: "User", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  namespace :admin do
    root "dashboard#index"
    resources :dashboard, only: [ :index ]
    resources :ice_creams
  end
  resources :ices, only: [ :index, :show, :new, :create ]

  resources :ajigraf, only: [ :index, :new, :create ] do
    collection do
      get "result", to: "ajigraf#result"
    end
  end

  # ネストされたルーティング(reviewsはice_creamsの子リソース)
  resources :ice_creams,  only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
    resources :reviews, only: [ :create, :destroy ]
    collection do
      get :favorites
      get :tags
      get :gotouchi
      get :calorie
    end
  end

  resources :favorites, only: [ :create, :destroy, :index ]

  resources :todayice, only: [ :index ] do
    collection do
      get "result"
    end
  end

  resources :images, only: [] do
    collection do
      get :ajigraf
      get :todayice
    end
  end

  resources :quizzes, only: [ :index ] do
    collection do
      post :check
      get :result
      get :explanation
    end
  end

  get "rakuten_search" => "ice_creams#search"


  devise_for :admins,
    controllers: { sessions: "admin/sessions" },
    path: "admin",
    skip: [ :registrations, :passwords ]

  post "/callback" => "linebot#callback"

  namespace :api do
    resources :ice_creams, only: [ :index ]
  end


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/today_ice.rb
class TodayIce < ApplicationRecord
  belongs_to :ice_cream
  before_create :set_uuid

  private
  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/todayice_controller.rb
class TodayiceController < ApplicationController
  # ログイン不要でアクセス可能にする
  skip_before_action :authenticate_user!, raise: false
  def index
  end

  def result
    # model側のset_uuidメソッドを使用してrecordの作成前にUUIDを割り振っている
    if params[:uuid].present?
      # if文の内容はsnsシェアからアクセスされた場合の処理
      today_ice_record = TodayIce.find_by(uuid: params[:uuid])
        if today_ice_record.nil?
          redirect_to todayice_index_path, alert: "指定されたアイスが見つかりませんでした。"
          return
        end
      @today_ice = today_ice_record&.ice_cream
      @today_ice_uuid = today_ice_record&.uuid
    else
      ice = IceCream.order("RANDOM()").first
      today_ice = TodayIce.create(ice_cream: ice)
      @today_ice = ice
      @today_ice_uuid = today_ice.uuid
    end
    @chart = @today_ice.chart
    @image = @today_ice.image
    prepare_meta_tags
  end

  private

  def prepare_meta_tags
    image_url = "#{request.base_url}/images/ajigraf?text=#{CGI.escape(@today_ice.name)}"
    set_meta_tags og: {
                    title: "きょうのあいすは#{@today_ice.name}!",
                    description: "#{@today_ice.name}があなたにおすすめのアイスです！",
                    type: "website",
                    url: request.original_url,
                    image: image_url
                  },
                  twitter: {
                    card: "summary_large_image",
                    title: "きょうのあいすは#{@today_ice.name}!",
                    description: "#{@today_ice.name}があなたにおすすめのアイスです！",
                    image: image_url
                  }
  end
end

app/views/todayice/_favorite.html.erb
<%= link_to favorites_path(ice_cream_id: ice_cream.id), id: "js-favotite-button-for-ice_cream-#{ice_cream.id}",  data: { turbo_method: :post } do %>
    <iconify-icon icon="mdi:heart-outline" width="24" height="24" class="text-red-500"></iconify-icon>
<% end %>

app/views/todayice/_favorite_button.html.erb
<% if current_user %>    
    <% if current_user.favorite?(ice_cream) %>
        <%= render 'unfavorite', {ice_cream: ice_cream} %>
    <% else %>
        <%= render 'favorite', {ice_cream: ice_cream} %>    
    <% end %>
<% end %>

app/views/todayice/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(ice_cream_id: ice_cream.id)), id: "js-favorite-button-for-ice_cream-#{ice_cream.id}",  data: { turbo_method: :delete} do %>
    <iconify-icon icon="mdi:heart" width="24" height="24" class="text-red-500"></iconify-icon>
<% end %>

app/views/todayice/index.html.erb
<h1 class="pt-10 font-kiwi text-4xl text-black-600 text-center" >
    きょうのあいす
</h1>

<h3 class="text-center font-kiwi text-lg mt-4 pt-16">
    きょうの食べるあいすをランダムに決めます🍨
</h3>
<h3 class="text-center font-kiwi text-lg mt-4">
    きょう食べるあいすに迷ってしまったときに🍦
</h3>
<h3 class="text-center font-kiwi text-lg mt-4">
    あいすを食べ忘れそうになってしまったときに🍧
</h3>
<div class="pt-10 flex justify-center gap-4 mt-1">
    <div class="flex justify-center">
        <%= link_to  result_todayice_index_path, data: { turbo: false }, class: "bg-stone-300 hover:bg-stone-400 text-stone-800 font-kiwi py-2 px-4 rounded-3xl flex justify-center items-center gap-2 w-80 h-24 text-lg" do %>
            <iconify-icon icon="game-icons:perspective-dice-six-faces-random" width="24" height="24"></iconify-icon>
            <span>きょうたべるあいすをきめる</span>
        <% end %>
    </div>
</div>  

app/views/todayice/result.html.erb
<h1 class="pt-10 font-kiwi text-4xl text-black-600 text-center">
    きょうのあいすは…
</h1>
<div class="mx-auto bg-amber-50 shadow-md rounded-lg p-6 max-w-5xl mt-6 text-center">
    <%= turbo_frame_tag "ice_result" do %>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-8">
            <div class="pl-4">
                <div class="flex flex-col items-center mt-6">
                    <h1 class="text-4xl font-kiwi"> <%= @today_ice.name %> </h1>
                    <%= link_to '🔎このあいすの詳細', ice_cream_path(@today_ice), data: {turbo: false}, class: ' hover:underline mt-2 font-kiwi' %>
                    <h2 class="text-3xl font-kiwi"> <%= @today_ice.comment %> </h2>
                    <% if @today_ice.image.attached? %>
                        <h3 class="pt-10"><%= image_tag @today_ice.image, class: 'h-40 w-auto' %></h3>
                    <% else %>
                        <h3 class="pt-10"><%= image_tag 'Icecream.png', class: 'h-40 w-auto' %></h3>
                    <% end %>    
                </div>
            </div>
            <div class="pl-4">
                <div data-controller="ice-cream-chart"
                    data-ice-cream-chart-chart-data-value="<%= @chart.to_vector.to_json %>"
                    data-ice-cream-chart-labels-value="<%= ['甘さ', '爽やかさ', '濃厚さ', 'カロリー', '具材の充実感'].to_json %>">
                    <canvas data-ice-cream-chart-target="canvas" width="400" height="200"></canvas>
                </div>
            </div>
        </div>
    <% end %>
    
    <div class="pt-4 flex justify-center mt-auto">
        <%= render 'favorite_button', ice_cream: @today_ice %>
    </div>

    <div class="pt-5 flex justify-center font-kiwi gap-4 mt-1">
        <%= link_to  result_todayice_index_path, class: "bg-stone-300 hover:bg-stone-400 text-stone-800 font-bold py-4 px-8 text-xl rounded-3xl flex items-center gap-2", data: { turbo: false} do %>
            <iconify-icon icon="game-icons:perspective-dice-six-faces-random" width="24" height="24"></iconify-icon>
            <span>もう一度</span>
        <% end %>
    </div>

    <div class="twitter pt-5 flex justify-center font-kiwi gap-4 mt-1">
        <%= link_to "https://twitter.com/intent/tweet?" + "text=きょうのあいすは#{@today_ice.name}!\n次はどのあいすが出るか試してみよう" + "&url=#{request.base_url}#{request.path}?uuid=#{@today_ice_uuid}", class: "bg-blue-400 hover:bg-blue-500 text-white font-kiwi py-4 px-8 text-xl rounded-3xl flex items-center gap-2 twitter-share-button", target: "_blank", rel: "noopener" do %>
            <iconify-icon icon="simple-icons:x" width="24" height="24"></iconify-icon>
            <span>結果をツイートする</span>
        <% end %>
    </div>
</div>